### ISSUE TITLE
nurl.parse alters the URL

### ISSUE THREAD

**Issue by Artmobile** [codeinthehole/nurl#2]
The parse method alters the original URL by making all of its parts lower case. The URL case must be preserved.

**Comment by ChristophP** [comment]
I ran into this issue as well. The library is great and very useful thank you.
But the lowercasing is a dealbreaker for us. We are implementing a link shortener/redirector and some links where we redirect to are case sensitive, for example amazon.
- https://www.amazon.de/dp/B007MP7OP0  -> this works
- https://www.amazon.de/dp/B007MP7Op0 -> this doesn't (note the lower case `p`)
@codeinthehole  would you consider changing this?
